### ISSUE TITLE
WebView is crashing on Android

### ISSUE THREAD

**Issue by HenryQuan** [HQAnime/AnimeGo-Re#32]
This is happening on my new device. Not sure if this is a WebView issue. It happens quite often and consistently because it is related to ads? I will try getting the crash log and see.

```
InputMethodManager: b/117267690: Failed to get fallback IMM with expected displayId=14 actual IMM#displayId=0 view=io.flutter.plugins.c.e{22b2bf9 VFEDHVC.. .F...... 0,0-2340,1080}
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.yihengquan.gogoanime, PID: 30597
E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1646)
E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1885)
E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1204)
E AndroidRuntime: 	at io.flutter.plugins.c.e$a.run(Unknown Source:26)
E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:239)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7500)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by HenryQuan** [comment]
Potentially related to https://github.com/flutter/flutter/issues/62022, https://github.com/flutter/flutter/issues/58229, https://github.com/flutter/flutter/issues/74412. However, I could never reproduce this on my other devices and so far nobody has asked about this 🤔. Nevertheless, the app crashes very consistently on this device, it is running Android 10 almost stock Android. I will have to attach a debugger to see what's wrong with webview_flutter and maybe this issue has been fixed in a later version.

**Comment by HenryQuan** [comment]
This is only happening on one device so I need to have a look.

**Comment by HenryQuan** [comment]
I can no longer reproduce this on that device. This should be fixed somehow.
